export interface Event {
  id: string
  name: string
  category: "concert" | "conference" | "comedy"
  date: string
  time: string
  venue: string
  description: string
  priceRange: string
  basePrice: number
  rows: number
  columns: number
  image: string
  availableSeats: number
  isTrending?: boolean
  ticketsSold?: number
}

export const mockEvents: Event[] = [
  {
    id: "1",
    name: "Summer Music Festival 2025",
    category: "concert",
    date: "2025-07-15",
    time: "18:00",
    venue: "Central Stadium",
    description: "Experience the biggest music festival of the summer with top artists from around the world.",
    priceRange: "$50 - $150",
    basePrice: 50,
    rows: 20,
    columns: 15,
    image: "/summer-music-festival-concert-stage.jpg",
    availableSeats: 250,
    isTrending: true,
    ticketsSold: 450,
  },
  {
    id: "2",
    name: "Tech Innovation Summit",
    category: "conference",
    date: "2025-06-20",
    time: "09:00",
    venue: "Convention Center",
    description: "Join industry leaders discussing the future of technology and innovation.",
    priceRange: "$100 - $300",
    basePrice: 100,
    rows: 15,
    columns: 20,
    image: "/technology-conference-summit-hall.jpg",
    availableSeats: 180,
    ticketsSold: 320,
  },
  {
    id: "3",
    name: "Comedy Night Live",
    category: "comedy",
    date: "2025-06-10",
    time: "20:00",
    venue: "Laugh Factory",
    description: "An evening of hilarious stand-up comedy with top comedians.",
    priceRange: "$30 - $80",
    basePrice: 30,
    rows: 12,
    columns: 10,
    image: "/comedy-club-stage-spotlight-microphone.jpg",
    availableSeats: 95,
    ticketsSold: 85,
  },
  {
    id: "4",
    name: "Jazz Under the Stars",
    category: "concert",
    date: "2025-07-25",
    time: "19:30",
    venue: "Riverside Amphitheater",
    description: "Smooth jazz performances in a beautiful outdoor setting.",
    priceRange: "$40 - $120",
    basePrice: 40,
    rows: 18,
    columns: 12,
    image: "/jazz-concert-outdoor-stage-night.jpg",
    availableSeats: 165,
    ticketsSold: 210,
  },
  {
    id: "5",
    name: "Business Leadership Forum",
    category: "conference",
    date: "2025-08-05",
    time: "08:30",
    venue: "Grand Hotel Conference Hall",
    description: "Network with executives and learn cutting-edge business strategies.",
    priceRange: "$150 - $400",
    basePrice: 150,
    rows: 10,
    columns: 15,
    image: "/business-conference-professional-meeting.jpg",
    availableSeats: 120,
    ticketsSold: 95,
  },
  {
    id: "6",
    name: "Stand-Up Spectacular",
    category: "comedy",
    date: "2025-06-28",
    time: "21:00",
    venue: "Comedy Club Downtown",
    description: "Back-to-back performances from rising comedy stars.",
    priceRange: "$25 - $60",
    basePrice: 25,
    rows: 10,
    columns: 8,
    image: "/comedy-show-stage-brick-wall.jpg",
    availableSeats: 65,
    ticketsSold: 55,
  },
  {
    id: "7",
    name: "Rock Legends Tour",
    category: "concert",
    date: "2025-08-20",
    time: "19:00",
    venue: "Arena Stadium",
    description: "Classic rock hits performed by legendary artists.",
    priceRange: "$60 - $200",
    basePrice: 60,
    rows: 25,
    columns: 20,
    image: "/rock-concert-arena-stage-lights.jpg",
    availableSeats: 400,
    ticketsSold: 380,
  },
  {
    id: "8",
    name: "Digital Marketing Expo",
    category: "conference",
    date: "2025-07-10",
    time: "10:00",
    venue: "Tech Park Auditorium",
    description: "Learn the latest digital marketing trends and strategies.",
    priceRange: "$80 - $250",
    basePrice: 80,
    rows: 12,
    columns: 18,
    image: "/digital-marketing-conference-presentation.jpg",
    availableSeats: 145,
    ticketsSold: 160,
  },
  {
    id: "9",
    name: "Improv Comedy Battle",
    category: "comedy",
    date: "2025-07-05",
    time: "20:30",
    venue: "Improv Theater",
    description: "Hilarious improvised comedy where anything can happen.",
    priceRange: "$20 - $50",
    basePrice: 20,
    rows: 8,
    columns: 10,
    image: "/improv-comedy-theater-stage.jpg",
    availableSeats: 55,
    ticketsSold: 48,
  },
  {
    id: "10",
    name: "Electronic Dance Festival",
    category: "concert",
    date: "2025-08-30",
    time: "17:00",
    venue: "Outdoor Festival Grounds",
    description: "The biggest EDM artists spinning all night long.",
    priceRange: "$70 - $180",
    basePrice: 70,
    rows: 30,
    columns: 25,
    image: "/electronic-dance-music-festival-stage-lights.jpg",
    availableSeats: 550,
    ticketsSold: 420,
  },
  {
    id: "11",
    name: "Startup Founder Conference",
    category: "conference",
    date: "2025-09-15",
    time: "09:00",
    venue: "Innovation Hub",
    description: "Connect with successful entrepreneurs and investors.",
    priceRange: "$120 - $350",
    basePrice: 120,
    rows: 14,
    columns: 16,
    image: "/startup-conference-innovation-tech.jpg",
    availableSeats: 170,
    ticketsSold: 140,
  },
  {
    id: "12",
    name: "Comedy Roast Battle",
    category: "comedy",
    date: "2025-06-18",
    time: "22:00",
    venue: "Underground Comedy Vault",
    description: "Comedians face off in epic roast battles.",
    priceRange: "$35 - $75",
    basePrice: 35,
    rows: 9,
    columns: 9,
    image: "/comedy-roast-battle-stage-spotlight.jpg",
    availableSeats: 70,
    ticketsSold: 62,
  },
]

export function getTrendingEvent(): Event | null {
  const trendingEvent = mockEvents.find((event) => event.isTrending)
  if (trendingEvent) return trendingEvent

  const sortedByTicketsSold = [...mockEvents].sort((a, b) => (b.ticketsSold || 0) - (a.ticketsSold || 0))
  return sortedByTicketsSold[0] || null
}
